"""Official CFA Institute 2027 Level II Learning Outcome Statements.

GENERATED FILE — do not hand-edit. Regenerate with:
    python3 extract_los.py ~/Downloads/2027-cfa_l2_topic_outline.pdf

Source: CFA Institute, "2027 Level II Topic Outlines" (10 topic areas,
51 learning modules, 382 LOS). Reference data only — the tick state lives
in the `los` table (see db.py), the same split as curriculum.py vs modules.

reading_no keys back to curriculum.READINGS, so the 51 official learning modules
fold into our 42 readings: reading 1 (Multiple Regression) is four official LMs and
reading 41 (Guidance for Standards I-VII) is seven, one per Standard. lm is kept per
row so the app can group a reading's LOS under the official module they came from.
"""

SOURCE = "CFA Institute — 2027 Level II Topic Outlines"

# (reading_no, official learning-module name, seq within reading, LOS text)
LOS = [
    # ---- R1: Multiple Regression
    (1, 'Basics of Multiple Regression and Underlying Assumptions', 1, 'describe the types of investment problems addressed by multiple linear regression and the regression process'),
    (1, 'Basics of Multiple Regression and Underlying Assumptions', 2, 'formulate a multiple linear regression model, describe the relation between the dependent variable and several independent variables, and interpret estimated regression coefficients'),
    (1, 'Basics of Multiple Regression and Underlying Assumptions', 3, 'explain the assumptions underlying a multiple linear regression model and interpret residual plots indicating potential violations of these assumptions'),
    (1, 'Evaluating Regression Model Fit and Interpreting Model Results', 4, 'evaluate how well a multiple regression model explains the dependent variable by analyzing ANOVA table results and measures of goodness of fit'),
    (1, 'Evaluating Regression Model Fit and Interpreting Model Results', 5, 'formulate hypotheses on the significance of two or more coefficients in a multiple regression model and interpret the results of the joint hypothesis tests'),
    (1, 'Evaluating Regression Model Fit and Interpreting Model Results', 6, 'calculate and interpret a predicted value for the dependent variable, given the estimated regression model and assumed values for the independent variable'),
    (1, 'Model Misspecification', 7, 'describe how model misspecification affects the results of a regression analysis and how to avoid common forms of misspecification'),
    (1, 'Model Misspecification', 8, 'explain the types of heteroskedasticity and how it affects statistical inference'),
    (1, 'Model Misspecification', 9, 'explain serial correlation and how it affects statistical inference'),
    (1, 'Model Misspecification', 10, 'explain multicollinearity and how it affects regression analysis'),
    (1, 'Extensions of Multiple Regression', 11, 'describe influence analysis and methods of detecting influential data points'),
    (1, 'Extensions of Multiple Regression', 12, 'formulate and interpret a multiple regression model that includes qualitative independent variables'),
    (1, 'Extensions of Multiple Regression', 13, 'formulate and interpret a logistic regression model'),
    # ---- R2: Time-Series Analysis
    (2, 'Time-Series Analysis', 1, 'calculate and evaluate the predicted trend value for a time series, modeled as either a linear trend or a log-linear trend, given the estimated trend coefficients'),
    (2, 'Time-Series Analysis', 2, 'describe factors that determine whether a linear or a log-linear trend should be used with a particular time series and evaluate limitations of trend models'),
    (2, 'Time-Series Analysis', 3, 'explain the requirement for a time series to be covariance stationary and describe the significance of a series that is not stationary'),
    (2, 'Time-Series Analysis', 4, 'describe the structure of an autoregressive (AR) model of order p and calculate one- and two-period-ahead forecasts given the estimated coefficients'),
    (2, 'Time-Series Analysis', 5, 'explain how autocorrelations of the residuals can be used to test whether the autoregressive model fits the time series'),
    (2, 'Time-Series Analysis', 6, 'explain mean reversion and calculate a mean-reverting level'),
    (2, 'Time-Series Analysis', 7, 'contrast in-sample and out-of-sample forecasts and compare the forecasting accuracy of different time-series models based on the root mean squared error criterion'),
    (2, 'Time-Series Analysis', 8, 'explain the instability of coefficients of time-series models'),
    (2, 'Time-Series Analysis', 9, 'describe characteristics of random walk processes and contrast them to covariance stationary processes'),
    (2, 'Time-Series Analysis', 10, 'describe implications of unit roots for time-series analysis, explain when unit roots are likely to occur and how to test for them, and demonstrate how a time series with a unit root can be transformed so it can be analyzed with an AR model'),
    (2, 'Time-Series Analysis', 11, 'describe the steps of the unit root test for nonstationarity and explain the relation of the test to autoregressive time-series models'),
    (2, 'Time-Series Analysis', 12, 'explain how to test and correct for seasonality in a time-series model and calculate and interpret a forecasted value using an AR model with a seasonal lag'),
    (2, 'Time-Series Analysis', 13, 'explain autoregressive conditional heteroskedasticity (ARCH) and describe how ARCH models can be applied to predict the variance of a time series'),
    (2, 'Time-Series Analysis', 14, 'explain how time-series variables should be analyzed for nonstationarity and/or cointegration before use in a linear regression'),
    (2, 'Time-Series Analysis', 15, 'determine an appropriate time-series model to analyze a given investment problem and justify that choice'),
    # ---- R3: Machine Learning
    (3, 'Machine Learning', 1, 'describe supervised machine learning, unsupervised machine learning, and deep learning'),
    (3, 'Machine Learning', 2, 'describe overfitting and identify methods of addressing it'),
    (3, 'Machine Learning', 3, 'describe supervised machine learning algorithms—including penalized regression, support vector machine, k-nearest neighbor, classification and regression tree, ensemble learning, and random forest—and determine the problems for which they are best suited'),
    (3, 'Machine Learning', 4, 'describe unsupervised machine learning algorithms—including principal components analysis, k-means clustering, and hierarchical clustering—and determine the problems for which they are best suited'),
    # ---- R4: Big Data Projects
    (4, 'Big Data Projects', 1, 'identify and explain steps in a data analysis project'),
    (4, 'Big Data Projects', 2, 'describe objectives, steps, and examples of preparing and wrangling data'),
    (4, 'Big Data Projects', 3, 'evaluate the fit of a machine learning algorithm'),
    (4, 'Big Data Projects', 4, 'describe objectives, methods, and examples of data exploration'),
    (4, 'Big Data Projects', 5, 'describe methods for extracting, selecting and engineering features from textual data'),
    (4, 'Big Data Projects', 6, 'describe objectives, steps, and techniques in model training'),
    (4, 'Big Data Projects', 7, 'describe preparing, wrangling, and exploring text-based data for financial forecasting'),
    # ---- R5: Currency Exchange Rates: Understanding Equilibrium Value
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 1, 'calculate and interpret the bid–offer spread on a spot or forward currency quotation and describe the factors that affect the bid–offer spread'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 2, 'identify a triangular arbitrage opportunity and calculate its profit, given the bid– offer quotations for three currencies'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 3, 'explain spot and forward rates and calculate the forward premium/discount for a given currency'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 4, 'calculate the mark-to-market value of a forward contract'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 5, 'explain international parity conditions (covered and uncovered interest rate parity, forward rate parity, purchasing power parity, and the international Fisher effect)'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 6, 'describe relations among the international parity conditions'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 7, 'evaluate the use of the current spot rate, the forward rate, purchasing power parity, and uncovered interest parity to forecast future spot exchange rates'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 8, 'explain approaches to assessing the long-run fair value of an exchange rate'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 9, 'describe the carry trade and its relation to uncovered interest rate parity and calculate the profit from a carry trade'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 10, 'explain how flows in the balance of payment accounts affect currency exchange rates'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 11, 'explain the potential effects of monetary and fiscal policy on exchange rates'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 12, 'describe objectives of central bank or government intervention and capital controls and describe the effectiveness of intervention and capital controls'),
    (5, 'Currency Exchange Rates: Understanding Equilibrium Value', 13, 'describe warning signs of a currency crisis'),
    # ---- R6: Economic Growth
    (6, 'Economic Growth', 1, 'compare factors favoring and limiting economic growth in developed and developing economies'),
    (6, 'Economic Growth', 2, 'describe the relation between the long-run rate of stock market appreciation and the sustainable growth rate of the economy'),
    (6, 'Economic Growth', 3, 'explain why potential GDP and its growth rate matter for equity and fixed income investors'),
    (6, 'Economic Growth', 4, 'contrast capital deepening investment and technological progress and explain how each affects economic growth and labor productivity'),
    (6, 'Economic Growth', 5, 'demonstrate forecasting potential GDP based on growth accounting relations'),
    (6, 'Economic Growth', 6, 'explain how natural resources affect economic growth and evaluate the argument that limited availability of natural resources constrains economic growth'),
    (6, 'Economic Growth', 7, 'explain how demographics, immigration, and labor force participation affect the rate and sustainability of economic growth'),
    (6, 'Economic Growth', 8, 'explain how investment in physical capital, human capital, and technological development affects economic growth'),
    (6, 'Economic Growth', 9, 'compare classical growth theory, neoclassical growth theory, and endogenous growth theory'),
    (6, 'Economic Growth', 10, 'explain and evaluate convergence hypotheses'),
    (6, 'Economic Growth', 11, 'describe the economic rationale for governments to provide incentives to private investment in technology and knowledge'),
    (6, 'Economic Growth', 12, 'describe the expected impact of removing trade barriers on capital investment and profits, employment and wages, and growth in the economies involved'),
    # ---- R7: Intercorporate Investments
    (7, 'Intercorporate Investments', 1, 'describe the classification, measurement, and disclosure under International Financial Reporting Standards (IFRS) for 1) investments in financial assets, 2) investments in associates, 3) joint ventures, 4) business combinations, and 5) special purpose and variable interest entities'),
    (7, 'Intercorporate Investments', 2, 'compare and contrast IFRS and US GAAP in their classification, measurement, and disclosure of investments in financial assets, investments in associates, joint ventures, business combinations, and special purpose and variable interest entities'),
    (7, 'Intercorporate Investments', 3, 'analyze how different methods used to account for intercorporate investments affect financial statements and ratios'),
    # ---- R8: Employee Compensation: Post-Employment and Share-Based
    (8, 'Employee Compensation: Post-Employment and Share-Based', 1, 'contrast types of employee compensation'),
    (8, 'Employee Compensation: Post-Employment and Share-Based', 2, 'explain how share-based compensation affects the financial statements'),
    (8, 'Employee Compensation: Post-Employment and Share-Based', 3, 'explain how to forecast share-based compensation expense and shares outstanding in a financial statement model and their use in valuation'),
    (8, 'Employee Compensation: Post-Employment and Share-Based', 4, 'explain how post-employment benefits affect the financial statements'),
    (8, 'Employee Compensation: Post-Employment and Share-Based', 5, 'explain financial modeling and valuation considerations for post-employment benefits'),
    # ---- R9: Multinational Operations
    (9, 'Multinational Operations', 1, 'compare and contrast presentation in (reporting) currency, functional currency, and local currency'),
    (9, 'Multinational Operations', 2, 'describe foreign currency transaction exposure, including accounting for and disclosures about foreign currency transaction gains and losses'),
    (9, 'Multinational Operations', 3, 'analyze how changes in exchange rates affect the translated sales of the subsidiary and parent company'),
    (9, 'Multinational Operations', 4, 'compare the current rate method and the temporal method, evaluate how each affects the parent company’s balance sheet and income statement, and determine which method is appropriate in various scenarios'),
    (9, 'Multinational Operations', 5, 'calculate the translation effects and evaluate the translation of a subsidiary’s balance sheet and income statement into the parent company’s presentation currency'),
    (9, 'Multinational Operations', 6, 'analyze how the current rate method and the temporal method affect financial statements and ratios'),
    (9, 'Multinational Operations', 7, 'analyze how alternative translation methods for subsidiaries operating in hyperinflationary economies affect financial statements and ratios'),
    (9, 'Multinational Operations', 8, 'describe how multinational operations affect a company’s effective tax rate'),
    (9, 'Multinational Operations', 9, 'explain how changes in the components of sales affect the sustainability of sales growth'),
    (9, 'Multinational Operations', 10, 'analyze how currency fluctuations potentially affect financial results, given a company’s countries of operation'),
    # ---- R10: Analysis of Financial Institutions
    (10, 'Analysis of Financial Institutions', 1, 'describe how financial institutions differ from other companies'),
    (10, 'Analysis of Financial Institutions', 2, 'describe key aspects of financial regulations of financial institutions'),
    (10, 'Analysis of Financial Institutions', 3, 'explain the CAMELS (capital adequacy, asset quality, management, earnings, liquidity, and sensitivity) approach to analyzing a bank, including key ratios and its limitations'),
    (10, 'Analysis of Financial Institutions', 4, 'analyze a bank based on financial statements and other factors'),
    (10, 'Analysis of Financial Institutions', 5, 'describe other factors to consider in analyzing a bank'),
    (10, 'Analysis of Financial Institutions', 6, 'describe key ratios and other factors to consider in analyzing an insurance company'),
    # ---- R11: Evaluating Quality of Financial Reports
    (11, 'Evaluating Quality of Financial Reports', 1, 'demonstrate the use of a conceptual framework for assessing the quality of a company’s financial reports'),
    (11, 'Evaluating Quality of Financial Reports', 2, 'explain potential problems that affect the quality of financial reports'),
    (11, 'Evaluating Quality of Financial Reports', 3, 'describe how to evaluate the quality of a company’s financial reports'),
    (11, 'Evaluating Quality of Financial Reports', 4, 'evaluate the quality of a company’s financial reports'),
    (11, 'Evaluating Quality of Financial Reports', 5, 'describe indicators of earnings quality'),
    (11, 'Evaluating Quality of Financial Reports', 6, 'describe the concept of sustainable (persistent) earnings'),
    (11, 'Evaluating Quality of Financial Reports', 7, 'explain mean reversion in earnings and how the accruals component of earnings affects the speed of mean reversion'),
    (11, 'Evaluating Quality of Financial Reports', 8, 'evaluate the earnings quality of a company'),
    (11, 'Evaluating Quality of Financial Reports', 9, 'evaluate the cash flow quality of a company'),
    (11, 'Evaluating Quality of Financial Reports', 10, 'describe indicators of balance sheet quality'),
    (11, 'Evaluating Quality of Financial Reports', 11, 'evaluate the balance sheet quality of a company'),
    (11, 'Evaluating Quality of Financial Reports', 12, 'describe indicators of cash flow quality'),
    (11, 'Evaluating Quality of Financial Reports', 13, 'describe sources of information about risk'),
    # ---- R12: Integration of Financial Statement Analysis Techniques
    (12, 'Integration of Financial Statement Analysis Techniques', 1, 'demonstrate the use of a framework for the analysis of financial statements, given a particular problem, question, or purpose (e.g., valuing equity based on comparables, critiquing a credit rating, obtaining a comprehensive picture of financial leverage, evaluating the perspectives given in management’s discussion of financial results)'),
    (12, 'Integration of Financial Statement Analysis Techniques', 2, 'identify financial reporting choices and biases that affect the quality and comparability of companies’ financial statements and explain how such biases may affect financial decisions'),
    (12, 'Integration of Financial Statement Analysis Techniques', 3, 'evaluate the quality of a company’s financial data and recommend appropriate adjustments to improve quality and comparability with similar companies, including adjustments for differences in accounting standards, methods, and assumptions'),
    (12, 'Integration of Financial Statement Analysis Techniques', 4, 'evaluate how a given change in accounting standards, methods, or assumptions affects financial statements and ratios'),
    (12, 'Integration of Financial Statement Analysis Techniques', 5, 'analyze and interpret how balance sheet modifications, earnings normalization, and cash flow statement related modifications affect a company’s financial statements, financial ratios, and overall financial condition'),
    # ---- R13: Analysis of Dividends and Share Repurchases
    (13, 'Analysis of Dividends and Share Repurchases', 1, 'describe the expected effect of regular cash dividends, extra dividends, liquidating dividends, stock dividends, stock splits, and reverse stock splits on shareholders’ wealth and a company’s financial ratios'),
    (13, 'Analysis of Dividends and Share Repurchases', 2, 'compare theories of dividend policy and explain implications of each for share value given a description of a corporate dividend action'),
    (13, 'Analysis of Dividends and Share Repurchases', 3, 'describe types of information (signals) that dividend initiations, increases, decreases, and omissions may convey'),
    (13, 'Analysis of Dividends and Share Repurchases', 4, 'explain how agency costs may affect a company’s payout policy'),
    (13, 'Analysis of Dividends and Share Repurchases', 5, 'explain factors that affect dividend policy in practice'),
    (13, 'Analysis of Dividends and Share Repurchases', 6, 'calculate and interpret the effective tax rate on a given currency unit of corporate earnings under double taxation, dividend imputation, and split-rate tax systems'),
    (13, 'Analysis of Dividends and Share Repurchases', 7, 'compare stable dividend with constant dividend payout ratio, and calculate the dividend under each policy'),
    (13, 'Analysis of Dividends and Share Repurchases', 8, 'describe broad trends in corporate payout policies'),
    (13, 'Analysis of Dividends and Share Repurchases', 9, 'compare share repurchase methods'),
    (13, 'Analysis of Dividends and Share Repurchases', 10, 'calculate and compare the effect of a share repurchase on earnings per share when 1) the repurchase is financed with the company’s surplus cash and 2) the company uses debt to finance the repurchase'),
    (13, 'Analysis of Dividends and Share Repurchases', 11, 'calculate the effect of a share repurchase on book value per share'),
    (13, 'Analysis of Dividends and Share Repurchases', 12, 'explain the choice between paying cash dividends and repurchasing shares'),
    (13, 'Analysis of Dividends and Share Repurchases', 13, 'calculate and interpret dividend coverage ratios based on 1) net income and 2) free cash flow'),
    (13, 'Analysis of Dividends and Share Repurchases', 14, 'identify characteristics of companies that may not be able to sustain their cash dividend'),
    # ---- R14: ESG Considerations in Investment Analysis
    (14, 'Environmental, Social, and Governance (ESG) Considerations in Investment Analysis', 1, 'describe global variations in ownership structures and the possible effects of these variations on corporate governance policies and practices'),
    (14, 'Environmental, Social, and Governance (ESG) Considerations in Investment Analysis', 2, 'evaluate the effectiveness of a company’s corporate governance policies and practices'),
    (14, 'Environmental, Social, and Governance (ESG) Considerations in Investment Analysis', 3, 'describe how ESG-related risk exposures and investment opportunities may be identified and evaluated'),
    (14, 'Environmental, Social, and Governance (ESG) Considerations in Investment Analysis', 4, 'evaluate ESG risk exposures and investment opportunities related to a company'),
    # ---- R15: Cost of Capital: Advanced Topics
    (15, 'Cost of Capital: Advanced Topics', 1, 'explain top-down and bottom-up factors that impact the cost of capital'),
    (15, 'Cost of Capital: Advanced Topics', 2, 'compare methods used to estimate the cost of debt'),
    (15, 'Cost of Capital: Advanced Topics', 3, 'explain historical and forward-looking approaches to estimating an equity risk premium'),
    (15, 'Cost of Capital: Advanced Topics', 4, 'compare methods used to estimate the required return on equity'),
    (15, 'Cost of Capital: Advanced Topics', 5, 'estimate the cost of debt or required return on equity for a public company and a private company'),
    (15, 'Cost of Capital: Advanced Topics', 6, 'evaluate a company’s capital structure and cost of capital relative to peers'),
    # ---- R16: Corporate Restructuring
    (16, 'Corporate Restructuring', 1, 'explain types of corporate restructurings and issuers’ motivations for pursuing them'),
    (16, 'Corporate Restructuring', 2, 'explain the initial evaluation of a corporate restructuring'),
    (16, 'Corporate Restructuring', 3, 'demonstrate valuation methods for, and interpret valuations of, companies involved in corporate restructurings'),
    (16, 'Corporate Restructuring', 4, 'demonstrate how corporate restructurings affect an issuer’s EPS, net debt to EBITDA ratio, and weighted average cost of capital'),
    (16, 'Corporate Restructuring', 5, 'evaluate corporate investment actions, including equity investments, joint ventures, and acquisitions'),
    (16, 'Corporate Restructuring', 6, 'evaluate corporate divestment actions, including sales and spin offs'),
    (16, 'Corporate Restructuring', 7, 'evaluate cost and balance sheet restructurings'),
    # ---- R17: Equity Valuation: Applications and Processes
    (17, 'Equity Valuation: Applications and Processes', 1, 'define valuation and intrinsic value and explain sources of perceived mispricing'),
    (17, 'Equity Valuation: Applications and Processes', 2, 'explain the going concern assumption and contrast a going concern value to a liquidation value'),
    (17, 'Equity Valuation: Applications and Processes', 3, 'describe definitions of value and justify which definition of value is most relevant to public company valuation'),
    (17, 'Equity Valuation: Applications and Processes', 4, 'describe applications of equity valuation'),
    (17, 'Equity Valuation: Applications and Processes', 5, 'describe questions that should be addressed in conducting an industry and competitive analysis'),
    (17, 'Equity Valuation: Applications and Processes', 6, 'contrast absolute and relative valuation models and describe examples of each type of model'),
    (17, 'Equity Valuation: Applications and Processes', 7, 'describe sum-of-the-parts valuation and conglomerate discounts'),
    (17, 'Equity Valuation: Applications and Processes', 8, 'explain broad criteria for choosing an appropriate approach for valuing a given company'),
    # ---- R18: Discounted Dividend Valuation
    (18, 'Discounted Dividend Valuation', 1, 'compare dividends, free cash flow, and residual income as inputs to discounted cash flow models and identify investment situations for which each measure is suitable'),
    (18, 'Discounted Dividend Valuation', 2, 'calculate and interpret the value of a common stock using the dividend discount model (DDM) for single and multiple holding periods'),
    (18, 'Discounted Dividend Valuation', 3, 'calculate the value of a common stock using the Gordon growth model and explain the model’s underlying assumptions'),
    (18, 'Discounted Dividend Valuation', 4, 'calculate the value of non-callable fixed-rate perpetual preferred stock'),
    (18, 'Discounted Dividend Valuation', 5, 'describe strengths and limitations of the Gordon growth model and justify its selection to value a company’s common shares'),
    (18, 'Discounted Dividend Valuation', 6, 'calculate and interpret the implied growth rate of dividends using the Gordon growth model and current stock price'),
    (18, 'Discounted Dividend Valuation', 7, 'calculate and interpret the present value of growth opportunities (PVGO) and the component of the leading price-to-earnings ratio (P/E) related to PVGO'),
    (18, 'Discounted Dividend Valuation', 8, 'calculate and interpret the justified leading and trailing P/Es using the Gordon growth model'),
    (18, 'Discounted Dividend Valuation', 9, 'estimate a required return based on any DDM, including the Gordon growth model and the H-model'),
    (18, 'Discounted Dividend Valuation', 10, 'evaluate whether a stock is overvalued, fairly valued, or undervalued by the market based on a DDM estimate of value'),
    (18, 'Discounted Dividend Valuation', 11, 'explain the growth phase, transition phase, and maturity phase of a business'),
    (18, 'Discounted Dividend Valuation', 12, 'explain the assumptions and justify the selection of the two-stage DDM, the H-model, the three-stage DDM, or spreadsheet modeling to value a company’s common shares'),
    (18, 'Discounted Dividend Valuation', 13, 'describe terminal value and explain alternative approaches to determining the terminal value in a DDM'),
    (18, 'Discounted Dividend Valuation', 14, 'calculate and interpret the value of common shares using the two-stage DDM, the H-model, and the three-stage DDM'),
    (18, 'Discounted Dividend Valuation', 15, 'explain the use of spreadsheet modeling to forecast dividends and to value common shares'),
    (18, 'Discounted Dividend Valuation', 16, 'calculate and interpret the sustainable growth rate of a company and demonstrate the use of DuPont analysis to estimate a company’s sustainable growth rate'),
    # ---- R19: Free Cash Flow Valuation
    (19, 'Free Cash Flow Valuation', 1, 'compare the free cash flow to the firm (FCFF) and free cash flow to equity (FCFE) approaches to valuation'),
    (19, 'Free Cash Flow Valuation', 2, 'explain the ownership perspective implicit in the FCFE approach'),
    (19, 'Free Cash Flow Valuation', 3, 'explain the appropriate adjustments to net income, earnings before interest and taxes (EBIT), earnings before interest, taxes, depreciation, and amortization (EBITDA), and cash flow from operations (CFO) to calculate FCFF and FCFE'),
    (19, 'Free Cash Flow Valuation', 4, 'calculate FCFF and FCFE'),
    (19, 'Free Cash Flow Valuation', 5, 'describe approaches for forecasting FCFF and FCFE'),
    (19, 'Free Cash Flow Valuation', 6, 'explain how dividends, share repurchases, share issues, and changes in leverage may affect future FCFF and FCFE'),
    (19, 'Free Cash Flow Valuation', 7, 'compare the FCFE model and dividend discount models'),
    (19, 'Free Cash Flow Valuation', 8, 'evaluate the use of net income and EBITDA as proxies for cash flow in valuation'),
    (19, 'Free Cash Flow Valuation', 9, 'explain the use of sensitivity analysis in FCFF and FCFE valuations'),
    (19, 'Free Cash Flow Valuation', 10, 'explain the single-stage (stable-growth), two-stage, and three-stage FCFF and FCFE models and justify the selection of the appropriate model given a company’s characteristics'),
    (19, 'Free Cash Flow Valuation', 11, 'estimate a company’s value using the appropriate free cash flow model(s)'),
    (19, 'Free Cash Flow Valuation', 12, 'describe approaches for calculating the terminal value in a multistage valuation model; and'),
    (19, 'Free Cash Flow Valuation', 13, 'evaluate whether a stock is overvalued, fairly valued, or undervalued based on a free cash flow valuation model'),
    # ---- R20: Market-Based Valuation: Price and Enterprise Value Multiples
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 1, 'contrast the method of comparables and the method based on forecasted fundamentals as approaches to using price multiples in valuation and explain economic rationales for each approach'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 2, 'calculate and interpret a justified price multiple'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 3, 'describe rationales for and possible drawbacks to using alternative price multiples and dividend yield in valuation'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 4, 'calculate and interpret alternative price multiples and dividend yield'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 5, 'calculate and interpret underlying earnings, explain methods of normalizing earnings per share (EPS), and calculate normalized EPS'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 6, 'explain and justify the use of earnings yield (E/P)'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 7, 'describe fundamental factors that influence alternative price multiples and dividend yield'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 8, 'calculate and interpret a predicted P/E, given a cross-sectional regression on fundamentals, and explain limitations to the cross-sectional regression methodology'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 9, 'calculate and interpret the justified price-to-earnings ratio (P/E), price-to-book ratio (P/B), and price-to-sales ratio (P/S) for a stock, based on forecasted fundamentals'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 10, 'calculate and interpret the P/E-to-growth (PEG) ratio and explain its use in relative valuation'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 11, 'calculate and explain the use of price multiples in determining terminal value in a multistage discounted cash flow (DCF) model'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 12, 'evaluate whether a stock is overvalued, fairly valued, or undervalued based on comparisons of multiples'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 13, 'evaluate a stock by the method of comparables and explain the importance of fundamentals in using the method of comparables'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 14, 'explain alternative definitions of cash flow used in price and enterprise value (EV) multiples and describe limitations of each definition'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 15, 'calculate and interpret EV multiples and evaluate the use of EV/EBITDA'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 16, 'explain sources of differences in cross-border valuation comparisons'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 17, 'describe momentum indicators and their use in valuation'),
    (20, 'Market-Based Valuation: Price and Enterprise Value Multiples', 18, 'explain the use of the arithmetic mean, the harmonic mean, the weighted harmonic mean, and the median to describe the central tendency of a group of multiples'),
    # ---- R21: Residual Income Valuation
    (21, 'Residual Income Valuation', 1, 'calculate and interpret residual income, economic value added, and market value added'),
    (21, 'Residual Income Valuation', 2, 'describe the uses of residual income models'),
    (21, 'Residual Income Valuation', 3, 'calculate the intrinsic value of a common stock using the residual income model and compare value recognition in residual income and other present value models'),
    (21, 'Residual Income Valuation', 4, 'explain fundamental determinants of residual income'),
    (21, 'Residual Income Valuation', 5, 'explain the relation between residual income valuation and the justified price-to-book ratio based on forecasted fundamentals'),
    (21, 'Residual Income Valuation', 6, 'calculate and interpret the intrinsic value of a common stock using single-stage (constant-growth) and multistage residual income models'),
    (21, 'Residual Income Valuation', 7, 'calculate the implied growth rate in residual income, given the market price-to-book ratio and an estimate of the required rate of return on equity'),
    (21, 'Residual Income Valuation', 8, 'explain continuing residual income and justify an estimate of continuing residual income at the forecast horizon, given company and industry prospects'),
    (21, 'Residual Income Valuation', 9, 'compare residual income models to dividend discount and free cash flow models'),
    (21, 'Residual Income Valuation', 10, 'explain strengths and weaknesses of residual income models and justify the selection of a residual income model to value a company’s common stock'),
    (21, 'Residual Income Valuation', 11, 'describe accounting issues in applying residual income models'),
    # ---- R22: Private Company Valuation
    (22, 'Private Company Valuation', 1, 'contrast important public and private company features for valuation purposes'),
    (22, 'Private Company Valuation', 2, 'describe uses of private business valuation and explain key areas of focus for financial analysts'),
    (22, 'Private Company Valuation', 3, 'explain cash flow estimation issues related to private companies and adjustments required to estimate normalized earnings'),
    (22, 'Private Company Valuation', 4, 'explain factors that require adjustment when estimating the discount rate for private companies'),
    (22, 'Private Company Valuation', 5, 'compare models used to estimate the required rate of return to private company equity (for example, the CAPM, the expanded CAPM, and the build-up approach)'),
    (22, 'Private Company Valuation', 6, 'explain and evaluate the effects on private company valuations of discounts and premiums based on control and marketability'),
    (22, 'Private Company Valuation', 7, 'explain the income, market, and asset-based approaches to private company valuation and factors relevant to the selection of each approach'),
    (22, 'Private Company Valuation', 8, 'calculate the value of a private company using income-based methods'),
    (22, 'Private Company Valuation', 9, 'calculate the value of a private company using market-based methods and describe the advantages and disadvantages of each method'),
    # ---- R23: The Term Structure and Interest Rate Dynamics
    (23, 'The Term Structure and Interest Rate Dynamics', 1, 'describe relationships among spot rates, forward rates, yield to maturity, expected and realized returns on bonds, and the shape of the yield curve'),
    (23, 'The Term Structure and Interest Rate Dynamics', 2, 'describe how zero-coupon rates (spot rates) may be obtained from the par curve by bootstrapping'),
    (23, 'The Term Structure and Interest Rate Dynamics', 3, 'describe the assumptions concerning the evolution of spot rates in relation to forward rates implicit in active bond portfolio management'),
    (23, 'The Term Structure and Interest Rate Dynamics', 4, 'describe the strategy of rolling down the yield curve'),
    (23, 'The Term Structure and Interest Rate Dynamics', 5, 'explain the swap rate curve and why and how market participants use it in valuation'),
    (23, 'The Term Structure and Interest Rate Dynamics', 6, 'calculate and interpret the swap spread for a given maturity'),
    (23, 'The Term Structure and Interest Rate Dynamics', 7, 'describe short-term interest rate spreads used to gauge economy-wide credit risk and liquidity risk'),
    (23, 'The Term Structure and Interest Rate Dynamics', 8, 'explain traditional theories of the term structure of interest rates and describe the implications of each theory for forward rates and the shape of the yield curve'),
    (23, 'The Term Structure and Interest Rate Dynamics', 9, 'explain how a bond’s exposure to each of the factors driving the yield curve can be measured and how these exposures can be used to manage yield curve risks'),
    (23, 'The Term Structure and Interest Rate Dynamics', 10, 'explain the maturity structure of yield volatilities and their effect on price volatility'),
    (23, 'The Term Structure and Interest Rate Dynamics', 11, 'explain how key economic factors are used to establish a view on benchmark rates, spreads, and yield curve changes'),
    # ---- R24: The Arbitrage-Free Valuation Framework
    (24, 'The Arbitrage-Free Valuation Framework', 1, 'explain what is meant by arbitrage-free valuation of a fixed-income instrument'),
    (24, 'The Arbitrage-Free Valuation Framework', 2, 'calculate the arbitrage-free value of an option-free, fixed-rate coupon bond'),
    (24, 'The Arbitrage-Free Valuation Framework', 3, 'describe a binomial interest rate tree framework'),
    (24, 'The Arbitrage-Free Valuation Framework', 4, 'describe the process of calibrating a binomial interest rate tree to match a specific term structure'),
    (24, 'The Arbitrage-Free Valuation Framework', 5, 'describe the backward induction valuation methodology and calculate the value of a fixed-income instrument given its cash flow at each node'),
    (24, 'The Arbitrage-Free Valuation Framework', 6, 'compare pricing using the zero-coupon yield curve with pricing using an arbitrage-free binomial lattice'),
    (24, 'The Arbitrage-Free Valuation Framework', 7, 'describe pathwise valuation in a binomial interest rate framework and calculate the value of a fixed-income instrument given its cash flows along each path'),
    (24, 'The Arbitrage-Free Valuation Framework', 8, 'describe a Monte Carlo forward-rate simulation and its application'),
    (24, 'The Arbitrage-Free Valuation Framework', 9, 'describe term structure models and how they are used'),
    # ---- R25: Valuation and Analysis of Bonds with Embedded Options
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 1, 'describe fixed-income securities with embedded options'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 2, 'explain the relationships between the values of a callable or putable bond, the underlying option-free (straight) bond, and the embedded option'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 3, 'describe how the arbitrage-free framework can be used to value a bond with embedded options'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 4, 'explain how interest rate volatility affects the value of a callable or putable bond'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 5, 'explain how changes in the level and shape of the yield curve affect the value of a callable or putable bond'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 6, 'calculate the value of a callable or putable bond from an interest rate tree'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 7, 'explain the calculation and use of option-adjusted spreads'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 8, 'explain how interest rate volatility affects option-adjusted spreads'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 9, 'calculate and interpret effective duration of a callable or putable bond'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 10, 'compare effective durations of callable, putable, and straight bonds'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 11, 'describe the use of one-sided durations and key rate durations to evaluate the interest rate sensitivity of bonds with embedded options'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 12, 'compare effective convexities of callable, putable, and straight bonds'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 13, 'calculate the value of a capped or floored floating-rate bond'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 14, 'describe defining features of a convertible bond'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 15, 'calculate and interpret the components of a convertible bond’s value'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 16, 'describe how a convertible bond is valued in an arbitrage-free framework'),
    (25, 'Valuation and Analysis of Bonds with Embedded Options', 17, 'compare the risk–return characteristics of a convertible bond with the risk– return characteristics of a straight bond and of the underlying common stock'),
    # ---- R26: Credit Analysis Models
    (26, 'Credit Analysis Models', 1, 'explain expected exposure, the loss given default, the probability of default, and the credit valuation adjustment'),
    (26, 'Credit Analysis Models', 2, 'explain credit scores and credit ratings'),
    (26, 'Credit Analysis Models', 3, 'calculate the expected return on a bond given transition in its credit rating'),
    (26, 'Credit Analysis Models', 4, 'explain structural and reduced-form models of corporate credit risk, including assumptions, strengths, and weaknesses'),
    (26, 'Credit Analysis Models', 5, 'calculate the value of a bond and its credit spread, given assumptions about the credit risk parameters'),
    (26, 'Credit Analysis Models', 6, 'interpret changes in a credit spread'),
    (26, 'Credit Analysis Models', 7, 'explain the determinants of the term structure of credit spreads and interpret a term structure of credit spreads'),
    (26, 'Credit Analysis Models', 8, 'compare the credit analysis required for securitized debt to the credit analysis of corporate debt'),
    # ---- R27: Credit Default Swaps
    (27, 'Credit Default Swaps', 1, 'describe credit default swaps (CDS), single-name and index CDS, and the parameters that define a given CDS product'),
    (27, 'Credit Default Swaps', 2, 'describe credit events and settlement protocols with respect to CDS'),
    (27, 'Credit Default Swaps', 3, 'explain the principles underlying and factors that influence the market’s pricing of CDS'),
    (27, 'Credit Default Swaps', 4, 'describe the use of CDS to manage credit exposures and to express views regarding changes in the shape and/or level of the credit curve'),
    (27, 'Credit Default Swaps', 5, 'describe the use of CDS to take advantage of valuation disparities among separate markets, such as bonds, loans, equities, and equity-linked instruments'),
    # ---- R28: Pricing and Valuation of Forward Commitments
    (28, 'Pricing and Valuation of Forward Commitments', 1, 'describe how equity forwards and futures are priced, and calculate and interpret their no-arbitrage value'),
    (28, 'Pricing and Valuation of Forward Commitments', 2, 'describe the carry arbitrage model without underlying cash flows and with underlying cash flows'),
    (28, 'Pricing and Valuation of Forward Commitments', 3, 'describe how interest rate forwards and futures are priced, and calculate and interpret their no-arbitrage value'),
    (28, 'Pricing and Valuation of Forward Commitments', 4, 'describe how fixed-income forwards and futures are priced, and calculate and interpret their no-arbitrage value'),
    (28, 'Pricing and Valuation of Forward Commitments', 5, 'describe how interest rate swaps are priced, and calculate and interpret their no-arbitrage value'),
    (28, 'Pricing and Valuation of Forward Commitments', 6, 'describe how currency swaps are priced, and calculate and interpret their no-arbitrage value'),
    (28, 'Pricing and Valuation of Forward Commitments', 7, 'describe how equity swaps are priced, and calculate and interpret their no-arbitrage value'),
    # ---- R29: Valuation of Contingent Claims
    (29, 'Valuation of Contingent Claims', 1, 'describe and interpret the binomial option valuation model and its component terms'),
    (29, 'Valuation of Contingent Claims', 2, 'describe how the value of a European option can be analyzed as the present value of the option’s expected payoff at expiration'),
    (29, 'Valuation of Contingent Claims', 3, 'identify an arbitrage opportunity involving options and describe the related arbitrage'),
    (29, 'Valuation of Contingent Claims', 4, 'calculate the no-arbitrage values of European and American options using a two-period binomial model'),
    (29, 'Valuation of Contingent Claims', 5, 'calculate and interpret the value of an interest rate option using a two-period binomial model'),
    (29, 'Valuation of Contingent Claims', 6, 'identify assumptions of the Black–Scholes–Merton option valuation model'),
    (29, 'Valuation of Contingent Claims', 7, 'interpret the components of the Black–Scholes–Merton model as applied to call options in terms of a leveraged position in the underlying'),
    (29, 'Valuation of Contingent Claims', 8, 'describe how the Black–Scholes–Merton model is used to value European options on equities and currencies'),
    (29, 'Valuation of Contingent Claims', 9, 'describe how the Black model is used to value European options on futures'),
    (29, 'Valuation of Contingent Claims', 10, 'describe how the Black model is used to value European interest rate options and European swaptions'),
    (29, 'Valuation of Contingent Claims', 11, 'interpret each of the option Greeks'),
    (29, 'Valuation of Contingent Claims', 12, 'describe how a delta hedge is executed'),
    (29, 'Valuation of Contingent Claims', 13, 'describe the role of gamma risk in options trading'),
    (29, 'Valuation of Contingent Claims', 14, 'define implied volatility and explain how it is used in options trading'),
    # ---- R30: Introduction to Commodities and Commodity Derivatives
    (30, 'Introduction to Commodities and Commodity Derivatives', 1, 'compare characteristics of commodity sectors'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 2, 'compare the life cycle of commodity sectors from production through trading or consumption'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 3, 'contrast the valuation of commodities with the valuation of equities and bonds'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 4, 'describe types of participants in commodity futures markets'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 5, 'analyze the relationship between spot prices and futures prices in markets in contango and markets in backwardation'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 6, 'compare theories of commodity futures returns'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 7, 'describe, calculate, and interpret the components of total return for a fully collateralized commodity futures contract'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 8, 'contrast roll return in markets in contango and markets in backwardation'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 9, 'describe how commodity swaps are used to obtain or modify exposure to commodities'),
    (30, 'Introduction to Commodities and Commodity Derivatives', 10, 'describe how the construction of commodity indexes affects index returns'),
    # ---- R31: Overview of Types of Real Estate Investment
    (31, 'Overview of Types of Real Estate Investment', 1, 'compare important real estate investment features for valuation purposes'),
    (31, 'Overview of Types of Real Estate Investment', 2, 'explain economic value drivers of real estate investments and their role in a portfolio'),
    (31, 'Overview of Types of Real Estate Investment', 3, 'discuss the distinctive investment characteristics of commercial property types'),
    (31, 'Overview of Types of Real Estate Investment', 4, 'explain the due diligence process and valuation approaches for real estate investments'),
    (31, 'Overview of Types of Real Estate Investment', 5, 'discuss real estate investment indexes, including their construction and potential biases'),
    # ---- R32: Investments in Real Estate through Publicly Traded Securities
    (32, 'Investments in Real Estate through Publicly Traded Securities', 1, 'discuss types of publicly traded real estate securities'),
    (32, 'Investments in Real Estate through Publicly Traded Securities', 2, 'justify the use of net asset value per share (NAVPS) in valuation of publicly traded real estate securities and estimate NAVPS based on forecasted cash net operating income'),
    (32, 'Investments in Real Estate through Publicly Traded Securities', 3, 'describe the use of funds from operations (FFO) and adjusted funds from operations (AFFO) in REIT valuation'),
    (32, 'Investments in Real Estate through Publicly Traded Securities', 4, 'calculate and interpret the value of a REIT share using the net asset value, relative value (price-to-FFO and price-to-AFFO), and discounted cash flow approaches'),
    (32, 'Investments in Real Estate through Publicly Traded Securities', 5, 'explain advantages and disadvantages of investing in real estate through publicly traded securities compared to private vehicles'),
    # ---- R33: Hedge Fund Strategies
    (33, 'Hedge Fund Strategies', 1, 'discuss how hedge fund strategies may be classified'),
    (33, 'Hedge Fund Strategies', 2, 'discuss investment characteristics, strategy implementation, and role in a portfolio of equity-related hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 3, 'discuss investment characteristics, strategy implementation, and role in a portfolio of event-driven hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 4, 'discuss investment characteristics, strategy implementation, and role in a portfolio of relative value hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 5, 'discuss investment characteristics, strategy implementation, and role in a portfolio of opportunistic hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 6, 'discuss investment characteristics, strategy implementation, and role in a portfolio of specialist hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 7, 'discuss investment characteristics, strategy implementation, and role in a portfolio of multi-manager hedge fund strategies'),
    (33, 'Hedge Fund Strategies', 8, 'describe how factor models may be used to understand hedge fund risk exposures'),
    (33, 'Hedge Fund Strategies', 9, 'evaluate the impact of an allocation to a hedge fund strategy in a traditional investment portfolio'),
    # ---- R34: Economics and Investment Markets
    (34, 'Economics and Investment Markets', 1, 'explain the notion that to affect market values, economic factors must affect one or more of the following: 1) default-free interest rates across maturities, 2) the timing and/or magnitude of expected cash flows, and 3) risk premiums'),
    (34, 'Economics and Investment Markets', 2, 'explain the role of expectations and changes in expectations in market valuation'),
    (34, 'Economics and Investment Markets', 3, 'explain the relationship between the long-term growth rate of the economy, the volatility of the growth rate, and the average level of real short-term interest rates'),
    (34, 'Economics and Investment Markets', 4, 'explain how the phase of the business cycle affects policy and short-term interest rates, the slope of the term structure of interest rates, and the relative performance of bonds of differing maturities'),
    (34, 'Economics and Investment Markets', 5, 'describe the factors that affect yield spreads between non-inflation-adjusted and inflation-indexed bonds'),
    (34, 'Economics and Investment Markets', 6, 'explain how the phase of the business cycle affects credit spreads and the performance of credit-sensitive fixed-income instruments'),
    (34, 'Economics and Investment Markets', 7, 'explain how the characteristics of the markets for a company’s products affect the company’s credit quality'),
    (34, 'Economics and Investment Markets', 8, 'explain the relationship between the consumption hedging properties of equity and the equity risk premium'),
    (34, 'Economics and Investment Markets', 9, 'explain how the phase of the business cycle affects short-term and long-term earnings growth expectations'),
    (34, 'Economics and Investment Markets', 10, 'describe cyclical effects on valuation multiples'),
    (34, 'Economics and Investment Markets', 11, 'describe the economic factors affecting investment in commercial real estate'),
    # ---- R35: Analysis of Active Portfolio Management
    (35, 'Analysis of Active Portfolio Management', 1, 'describe how value added by active management is measured'),
    (35, 'Analysis of Active Portfolio Management', 2, 'calculate and interpret the information ratio (ex post and ex ante) and contrast it to the Sharpe ratio'),
    (35, 'Analysis of Active Portfolio Management', 3, 'describe and interpret the fundamental law of active portfolio management, including its component terms—transfer coefficient, information coefficient, breadth, and active risk (aggressiveness)'),
    (35, 'Analysis of Active Portfolio Management', 4, 'explain how the information ratio may be useful in investment manager selection and choosing the level of active portfolio risk'),
    (35, 'Analysis of Active Portfolio Management', 5, 'compare active management strategies, including market timing and security selection, and evaluate strategy changes in terms of the fundamental law of active management'),
    (35, 'Analysis of Active Portfolio Management', 6, 'describe the practical strengths and limitations of the fundamental law of active management'),
    # ---- R36: Exchange-Traded Funds: Mechanics and Applications
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 1, 'explain the creation/redemption process of ETFs and the function of authorized participants'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 2, 'describe how ETFs are traded in secondary markets'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 3, 'describe sources of tracking error for ETFs'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 4, 'describe factors affecting ETF bid–ask spreads'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 5, 'describe sources of ETF premiums and discounts to NAV'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 6, 'describe costs of owning an ETF'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 7, 'describe types of ETF risk'),
    (36, 'Exchange-Traded Funds: Mechanics and Applications', 8, 'identify and describe portfolio uses of ETFs'),
    # ---- R37: Using Multifactor Models
    (37, 'Using Multifactor Models', 1, 'describe arbitrage pricing theory (APT), including its underlying assumptions and its relation to multifactor models'),
    (37, 'Using Multifactor Models', 2, 'define arbitrage opportunity and determine whether an arbitrage opportunity exists'),
    (37, 'Using Multifactor Models', 3, 'calculate the expected return on an asset given an asset’s factor sensitivities and the factor risk premiums'),
    (37, 'Using Multifactor Models', 4, 'describe and compare macroeconomic factor models, fundamental factor models, and statistical factor models'),
    (37, 'Using Multifactor Models', 5, 'describe uses of multifactor models and interpret the output of analyses based on multifactor models'),
    (37, 'Using Multifactor Models', 6, 'describe the potential benefits for investors in considering multiple risk dimensions when modeling asset returns'),
    (37, 'Using Multifactor Models', 7, 'explain sources of active risk and interpret tracking risk and the information ratio'),
    # ---- R38: Measuring and Managing Market Risk
    (38, 'Measuring and Managing Market Risk', 1, 'explain the use of value at risk (VaR) in measuring portfolio risk'),
    (38, 'Measuring and Managing Market Risk', 2, 'compare the parametric (variance–covariance), historical simulation, and Monte Carlo simulation methods for estimating VaR'),
    (38, 'Measuring and Managing Market Risk', 3, 'estimate and interpret VaR under the parametric, historical simulation, and Monte Carlo simulation methods'),
    (38, 'Measuring and Managing Market Risk', 4, 'describe advantages and limitations of VaR'),
    (38, 'Measuring and Managing Market Risk', 5, 'describe extensions of VaR'),
    (38, 'Measuring and Managing Market Risk', 6, 'describe sensitivity risk measures and scenario risk measures and compare these measures to VaR'),
    (38, 'Measuring and Managing Market Risk', 7, 'demonstrate how equity, fixed-income, and options exposure measures may be used in measuring and managing market risk and volatility risk'),
    (38, 'Measuring and Managing Market Risk', 8, 'describe the use of sensitivity risk measures and scenario risk measures'),
    (38, 'Measuring and Managing Market Risk', 9, 'describe advantages and limitations of sensitivity risk measures and scenario risk measures'),
    (38, 'Measuring and Managing Market Risk', 10, 'explain constraints used in managing market risks, including risk budgeting, position limits, scenario limits, and stop-loss limits'),
    (38, 'Measuring and Managing Market Risk', 11, 'explain how risk measures may be used in capital allocation decisions'),
    (38, 'Measuring and Managing Market Risk', 12, 'describe risk measures used by banks, asset managers, pension funds, and insurers'),
    # ---- R39: Backtesting and Simulation
    (39, 'Backtesting and Simulation', 1, 'describe objectives in backtesting an investment strategy'),
    (39, 'Backtesting and Simulation', 2, 'describe and contrast steps and procedures in backtesting an investment strategy'),
    (39, 'Backtesting and Simulation', 3, 'interpret metrics and visuals reported in a backtest of an investment strategy'),
    (39, 'Backtesting and Simulation', 4, 'identify problems in a backtest of an investment strategy'),
    (39, 'Backtesting and Simulation', 5, 'evaluate and interpret a historical scenario analysis'),
    (39, 'Backtesting and Simulation', 6, 'contrast Monte Carlo and historical simulation approaches'),
    (39, 'Backtesting and Simulation', 7, 'explain inputs and decisions in simulation and interpret a simulation and'),
    (39, 'Backtesting and Simulation', 8, 'demonstrate the use of sensitivity analysis'),
    # ---- R40: Code of Ethics and Standards of Professional Conduct
    (40, 'Code of Ethics and Standards of Professional Conduct', 1, 'describe the structure of the CFA Institute Professional Conduct Program and the disciplinary review process for the enforcement of the CFA Institute Code of Ethics and Standards of Professional Conduct'),
    (40, 'Code of Ethics and Standards of Professional Conduct', 2, 'explain the ethical responsibilities required by the Code and Standards, including the subsections of each standard'),
    # ---- R41: Guidance for Standards I-VII
    (41, 'Guidance for Standard I: Professionalism', 1, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by interpreting the Code and Standards in various situations involving issues of professional integrity'),
    (41, 'Guidance for Standard I: Professionalism', 2, 'recommend practices and procedures designed to prevent violations of the Code and Standards'),
    (41, 'Guidance for Standard II: Integrity of Capital Markets', 3, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard II: Integrity of Capital Markets', 4, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    (41, 'Guidance for Standard III: Duties to Clients', 5, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard III: Duties to Clients', 6, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    (41, 'Guidance for Standard IV: Duties to Employers', 7, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard IV: Duties to Employers', 8, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    (41, 'Guidance for Standard V: Investment Analysis, Recommendations, and Actions', 9, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard V: Investment Analysis, Recommendations, and Actions', 10, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    (41, 'Guidance for Standard VI: Conflicts of Interest', 11, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard VI: Conflicts of Interest', 12, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    (41, 'Guidance for Standard VII: Responsibilities as a CFA Institute Member or CFA Candidate', 13, 'demonstrate a thorough knowledge of the CFA Institute Code of Ethics and Standards of Professional Conduct by applying the Code and Standards to specific situations'),
    (41, 'Guidance for Standard VII: Responsibilities as a CFA Institute Member or CFA Candidate', 14, 'recommend practices and procedures designed to prevent violations of the Code of Ethics and Standards of Professional Conduct'),
    # ---- R42: Application of the Code and Standards: Level II
    (42, 'Application of the Code and Standards: Level II', 1, 'evaluate practices, policies, and conduct relative to the CFA Institute Code of Ethics and Standards of Professional Conduct'),
    (42, 'Application of the Code and Standards: Level II', 2, 'explain how the practices, policies, and conduct do or do not violate the CFA Institute Code of Ethics and Standards of Professional Conduct'),
]
